version: "3.7"

services:

  titan-postgres:
    container_name: titan-postgres
    image: postgres:latest
    restart: always
    volumes:
      - ~/data/postgres/titan:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - database.env
    ports:
      - 5432:5432


#  titan-server:
#    container_name: titan-server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    env_file:
#      - database.env
#    ports:
#      - 8081:8081
#    depends_on:
#      - titan-postgres