server:
  port: 8081
  servlet:
    context-path:
  error:
    include-message: ALWAYS

spring:
  application:
    name: titan
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${spring.application.name}
  datasource:
    username: titan_server
    password: hB!X[-mAPbEY5Ezp_<@
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:titan}
